`timescale 1ns / 1ps

// ============================================================================
// TESTBENCH: tb_vrm_axilite2nsi_mmio_64
//
// Description:
//   Integration testbench for the 64-bit AXI4-Lite to NSI MMIO bridge.
//
//   The testbench models an NSI register interface using a small register
//   array and connects it to the AXI4-Lite slave interface of the DUT.
//
//   Verification covers:
//     - AXI4-Lite write address channel
//     - AXI4-Lite write data channel
//     - Independent AW/W channel handshaking
//     - AXI4-Lite write response channel
//     - AXI4-Lite read address channel
//     - AXI4-Lite read data channel
//     - NSI MMIO write transaction generation
//     - NSI MMIO register readback
//     - Synchronous NSI read latency
//     - 64-bit data transfer
//
//   The AXI4-Lite master tasks intentionally handle the AW and W channels
//   independently to verify that the bridge does not depend on a specific
//   ordering between the two write channels.
//
// The dummy NSI register model uses address bits [5:3] to select one of
// eight 64-bit registers, matching the register-selection scheme expected
// by the corresponding NSI top-level integration.
// ============================================================================

module tb_vrm_axilite2nsi_mmio_64;

    // =========================================================================
    // 1. TESTBENCH PARAMETERS
    // =========================================================================
    parameter C_S_AXI_DATA_WIDTH = 64;
    parameter C_S_AXI_ADDR_WIDTH = 64;

    // =========================================================================
    // 2. CLOCK AND RESET SIGNALS
    // =========================================================================
    reg s_axi_aclk;
    reg s_axi_aresetn;

    // =========================================================================
    // 3. AXI4-LITE SLAVE INTERFACE
    // =========================================================================

    // -------------------------------------------------------------------------
    // Write Address Channel
    // -------------------------------------------------------------------------
    reg  [C_S_AXI_ADDR_WIDTH-1:0] s_axi_awaddr;
    reg                            s_axi_awvalid;
    wire                           s_axi_awready;

    // -------------------------------------------------------------------------
    // Write Data Channel
    // -------------------------------------------------------------------------
    reg  [C_S_AXI_DATA_WIDTH-1:0] s_axi_wdata;
    reg  [C_S_AXI_DATA_WIDTH/8-1:0] s_axi_wstrb;
    reg                            s_axi_wvalid;
    wire                           s_axi_wready;

    // -------------------------------------------------------------------------
    // Write Response Channel
    // -------------------------------------------------------------------------
    wire [1:0] s_axi_bresp;
    wire       s_axi_bvalid;
    reg        s_axi_bready;

    // -------------------------------------------------------------------------
    // Read Address Channel
    // -------------------------------------------------------------------------
    reg  [C_S_AXI_ADDR_WIDTH-1:0] s_axi_araddr;
    reg                            s_axi_arvalid;
    wire                           s_axi_arready;

    // -------------------------------------------------------------------------
    // Read Data Channel
    // -------------------------------------------------------------------------
    wire [C_S_AXI_DATA_WIDTH-1:0] s_axi_rdata;
    wire [1:0]                    s_axi_rresp;
    wire                           s_axi_rvalid;
    reg                            s_axi_rready;

    // =========================================================================
    // 4. NSI MMIO INTERFACE
    // =========================================================================
    // MMIO interface generated by the AXI4-Lite to NSI bridge.
    wire                              mmio_we;
    wire [C_S_AXI_ADDR_WIDTH-1:0]     mmio_addr;
    wire [C_S_AXI_DATA_WIDTH-1:0]     mmio_wdata;
    reg  [C_S_AXI_DATA_WIDTH-1:0]     mmio_rdata = 0;

    // =========================================================================
    // 5. DEVICE UNDER TEST
    // =========================================================================
    vrm_axilite2nsi_mmio_64 #(
        .C_S_AXI_DATA_WIDTH (C_S_AXI_DATA_WIDTH),
        .C_S_AXI_ADDR_WIDTH (C_S_AXI_ADDR_WIDTH)
    ) dut (
        .s_axi_aclk    (s_axi_aclk),
        .s_axi_aresetn (s_axi_aresetn),

        .s_axi_awaddr  (s_axi_awaddr),
        .s_axi_awvalid (s_axi_awvalid),
        .s_axi_awready (s_axi_awready),

        .s_axi_wdata   (s_axi_wdata),
        .s_axi_wstrb   (s_axi_wstrb),
        .s_axi_wvalid  (s_axi_wvalid),
        .s_axi_wready  (s_axi_wready),

        .s_axi_bresp   (s_axi_bresp),
        .s_axi_bvalid  (s_axi_bvalid),
        .s_axi_bready  (s_axi_bready),

        .s_axi_araddr  (s_axi_araddr),
        .s_axi_arvalid (s_axi_arvalid),
        .s_axi_arready (s_axi_arready),

        .s_axi_rdata   (s_axi_rdata),
        .s_axi_rresp   (s_axi_rresp),
        .s_axi_rvalid  (s_axi_rvalid),
        .s_axi_rready  (s_axi_rready),

        .mmio_we       (mmio_we),
        .mmio_addr     (mmio_addr),
        .mmio_wdata    (mmio_wdata),
        .mmio_rdata    (mmio_rdata)
    );

    // =========================================================================
    // 6. DUMMY NSI REGISTER MODEL
    // =========================================================================
    // Simple 8-entry, 64-bit register model used to emulate the downstream
    // NSI MMIO register interface.
    //
    // Address bits [5:3] select the register index:
    //
    //   mmio_addr[5:3] = 3'b000 -> Register 0
    //   mmio_addr[5:3] = 3'b001 -> Register 1
    //   ...
    //   mmio_addr[5:3] = 3'b111 -> Register 7
    //
    // This address decoding is consistent with the register layout used by
    // the corresponding NSI top-level integration.
    reg [63:0] dummy_reg [0:7];

    integer idx;

    initial begin
        for (idx = 0; idx < 8; idx = idx + 1)
            dummy_reg[idx] = 64'd0;
    end

    // -------------------------------------------------------------------------
    // NSI Register Access Model
    // -------------------------------------------------------------------------
    always @(posedge s_axi_aclk) begin

        // Synchronous MMIO write.
        if (mmio_we) begin
            dummy_reg[mmio_addr[5:3]] <= mmio_wdata;
        end

        // Synchronous MMIO read with one-cycle response latency.
        mmio_rdata <= dummy_reg[mmio_addr[5:3]];
    end

    // =========================================================================
    // 7. CLOCK GENERATION AND AXI4-LITE TRANSACTION TASKS
    // =========================================================================

    // 100 MHz clock: 10 ns period.
    initial begin
        s_axi_aclk = 0;
        forever #5 s_axi_aclk = ~s_axi_aclk;
    end

    // -------------------------------------------------------------------------
    // AXI4-Lite Write Transaction Task
    // -------------------------------------------------------------------------
    // The write address and write data channels are handled independently,
    // allowing the task to tolerate either channel becoming ready first.
    //
    // This prevents the testbench from making an implicit assumption that
    // AWREADY and WREADY are asserted in the same cycle.
    task axi_write;
        input [63:0] addr;
        input [63:0] data;
        begin

            @(posedge s_axi_aclk);

            s_axi_awaddr  <= addr;
            s_axi_wdata   <= data;
            s_axi_wstrb   <= 8'hFF;
            s_axi_awvalid <= 1'b1;
            s_axi_wvalid  <= 1'b1;
            s_axi_bready  <= 1'b1;

            // Handle AW and W channels independently.
            fork

                begin
                    do @(posedge s_axi_aclk);
                    while (!s_axi_awready);

                    s_axi_awvalid <= 1'b0;
                end

                begin
                    do @(posedge s_axi_aclk);
                    while (!s_axi_wready);

                    s_axi_wvalid <= 1'b0;
                end

            join

            // Wait for the AXI4-Lite write response.
            do @(posedge s_axi_aclk);
            while (!s_axi_bvalid);

            s_axi_bready <= 1'b0;
        end
    endtask

    // -------------------------------------------------------------------------
    // AXI4-Lite Read Transaction Task
    // -------------------------------------------------------------------------
    // Issues a read address and waits for the corresponding read data
    // response from the DUT.
    task axi_read(
        input  [63:0] addr,
        output [63:0] data
    );
        begin

            @(posedge s_axi_aclk);

            // Address phase.
            s_axi_araddr  <= addr;
            s_axi_arvalid <= 1'b1;
            s_axi_rready  <= 1'b1;

            // Wait for ARREADY before completing the address handshake.
            do @(posedge s_axi_aclk);
            while (!s_axi_arready);

            s_axi_arvalid <= 1'b0;

            // Wait for the read data response.
            do @(posedge s_axi_aclk);
            while (!s_axi_rvalid);

            data = s_axi_rdata;

            s_axi_rready <= 1'b0;
        end
    endtask

    // =========================================================================
    // 8. SIMULATION STIMULUS
    // =========================================================================
    reg [63:0] read_val = 0;

    initial begin

        // ---------------------------------------------------------------------
        // Waveform Dump
        // ---------------------------------------------------------------------
        $dumpfile("dump_axilite_mmio.vcd");
        $dumpvars(0, tb_vrm_axilite2nsi_mmio_64);

        // ---------------------------------------------------------------------
        // Initial Signal State
        // ---------------------------------------------------------------------
        s_axi_aresetn = 1'b0;

        s_axi_awaddr  = 0;
        s_axi_awvalid = 0;

        s_axi_wdata   = 0;
        s_axi_wstrb   = 0;
        s_axi_wvalid  = 0;
        s_axi_bready  = 0;

        s_axi_araddr  = 0;
        s_axi_arvalid = 0;
        s_axi_rready  = 0;

        // ---------------------------------------------------------------------
        // Reset Sequence
        // ---------------------------------------------------------------------
        #50;
        s_axi_aresetn = 1'b1;
        #50;

        $display("");
        $display("============================================================");
        $display("VRM AXI4-LITE TO NSI MMIO 64-BIT INTEGRATION TEST");
        $display("============================================================");

        // =====================================================================
        // 8.1 AXI4-LITE WRITE TEST
        // =====================================================================

        $display("");
        $display("[TEST] Writing configuration registers...");

        // Base address = 0x0000.
        //
        // Offset 0x08 -> Register 1
        // Used here as the SNN threshold configuration register.
        axi_write(
            64'h0000_0008,
            64'h0000_0000_0000_001E
        );

        $display(
            "[PASS] Write slv_reg1 (Threshold) = 0x1E"
        );

        // Offset 0x18 -> Register 3
        // Used here as the maximum chunk configuration register.
        axi_write(
            64'h0000_0018,
            64'h0000_0000_0000_0FFF
        );

        $display(
            "[PASS] Write slv_reg3 (Max Chunks) = 0xFFF"
        );

        #20;

        // =====================================================================
        // 8.2 AXI4-LITE READBACK TEST
        // =====================================================================

        $display("");
        $display("[TEST] Reading back configuration registers...");

        // ---------------------------------------------------------------------
        // Register 1 Readback
        // ---------------------------------------------------------------------
        axi_read(
            64'h0000_0008,
            read_val
        );

        if (read_val === 64'h0000_0000_0000_001E) begin

            $display(
                "[PASS] Readback slv_reg1 = %h",
                read_val
            );

        end else begin

            $display(
                "[FAIL] Readback slv_reg1 = %h, expected 000000000000001E",
                read_val
            );

        end

        // ---------------------------------------------------------------------
        // Register 3 Readback
        // ---------------------------------------------------------------------
        axi_read(
            64'h0000_0018,
            read_val
        );

        if (read_val === 64'h0000_0000_0000_0FFF) begin

            $display(
                "[PASS] Readback slv_reg3 = %h",
                read_val
            );

        end else begin

            $display(
                "[FAIL] Readback slv_reg3 = %h, expected 0000000000000FFF",
                read_val
            );

        end

        // =====================================================================
        // 8.3 END OF TEST
        // =====================================================================

        #50;

        $display("");
        $display("============================================================");
        $display("AXI4-LITE TO NSI MMIO VERIFICATION COMPLETED");
        $display("============================================================");
        $display("");

        $finish;

    end

endmodule
