`timescale 1ns / 1ps

// ============================================================================
// TESTBENCH: tb_vrm_axis_nsi_loopback
//
// Description:
//   Integration testbench for the AXI4-Stream to NSI and NSI to AXI4-Stream
//   data path.
//
//   The testbench connects the following modules through a shared dummy SRAM:
//
//       AXI4-Stream
//           |
//           v
//       vrm_axis2nsi_write
//           |
//           v
//       Dummy SRAM
//           |
//           v
//       vrm_nsi_read2axis
//           |
//           v
//       AXI4-Stream
//
// Verification covers:
//   - AXI4-Stream input data transfer
//   - NSI write address generation
//   - NSI write data transfer
//   - NSI read address generation
//   - One-cycle SRAM read latency
//   - AXI4-Stream output data integrity
//   - TLAST propagation
//   - Egress FIFO buffering
//   - AXI4-Stream backpressure handling
//
// The testbench uses a reduced FIFO depth to make FIFO behavior and
// backpressure conditions easier to observe during simulation.
// ============================================================================

module tb_vrm_axis_nsi_loopback;

    // =========================================================================
    // 1. TESTBENCH PARAMETERS
    // =========================================================================
    parameter DATA_W     = 32;
    parameter ADDR_W     = 12;
    parameter FIFO_DEPTH = 16;

    // =========================================================================
    // 2. CLOCK AND RESET SIGNALS
    // =========================================================================
    reg aclk;
    reg aresetn;

    // =========================================================================
    // 3. AXI4-STREAM INPUT INTERFACE
    // =========================================================================
    // Input stream connected to the AXI4-Stream to NSI writer.
    reg  [DATA_W-1:0] s_axis_tdata;
    reg               s_axis_tlast;
    reg               s_axis_tvalid;
    wire              s_axis_tready;

    // NSI write interface generated by the writer.
    wire              nsi_wr_en;
    wire [ADDR_W-1:0] nsi_wr_addr;
    wire [DATA_W-1:0] nsi_wr_data;
    wire              nsi_wr_valid;
    wire              nsi_wr_last;

    // =========================================================================
    // 4. AXI4-STREAM OUTPUT INTERFACE
    // =========================================================================
    // Output stream generated by the NSI reader.
    wire [DATA_W-1:0] m_axis_tdata;
    wire              m_axis_tlast;
    wire              m_axis_tvalid;
    reg               m_axis_tready;

    // Reader control interface.
    reg               ctrl_start_read;
    reg  [ADDR_W-1:0] ctrl_max_addr;
    wire              status_busy;

    // NSI read interface generated by the reader.
    wire              nsi_rd_en;
    wire [ADDR_W-1:0] nsi_rd_addr;
    wire [DATA_W-1:0] nsi_rd_data;

    // =========================================================================
    // 5. DUMMY SRAM MODEL
    // =========================================================================
    // Shared memory model used to connect the NSI write and read interfaces.
    //
    // The model provides:
    //   - Synchronous write behavior
    //   - One-cycle read latency
    //   - Direct data storage for loopback verification
    reg [DATA_W-1:0] dummy_sram [0:(1<<ADDR_W)-1];

    reg [DATA_W-1:0] sram_rd_data_reg = 0;

    always @(posedge aclk) begin

        // ---------------------------------------------------------------------
        // SRAM Write
        // ---------------------------------------------------------------------
        if (nsi_wr_en && nsi_wr_valid) begin
            dummy_sram[nsi_wr_addr] <= nsi_wr_data;
        end

        // ---------------------------------------------------------------------
        // SRAM Read
        // ---------------------------------------------------------------------
        // The dummy SRAM models a one-cycle read latency as expected by
        // vrm_nsi_read2axis.
        if (nsi_rd_en) begin
            sram_rd_data_reg <= dummy_sram[nsi_rd_addr];
        end
    end

    assign nsi_rd_data = sram_rd_data_reg;

    // =========================================================================
    // 6. DEVICE UNDER TEST
    // =========================================================================

    // -------------------------------------------------------------------------
    // DUT 1: AXI4-Stream to NSI Writer
    // -------------------------------------------------------------------------
    vrm_axis2nsi_write #(
        .DATA_W     (DATA_W),
        .ADDR_W     (ADDR_W),
        .FIFO_DEPTH (FIFO_DEPTH)
    ) dut_writer (
        .aclk             (aclk),
        .aresetn          (aresetn),

        .ctrl_reset_addr  (1'b0),

        .s_axis_tdata     (s_axis_tdata),
        .s_axis_tlast     (s_axis_tlast),
        .s_axis_tvalid    (s_axis_tvalid),
        .s_axis_tready    (s_axis_tready),

        .o_nsi_wr_en      (nsi_wr_en),
        .o_nsi_wr_addr    (nsi_wr_addr),
        .o_nsi_wr_data    (nsi_wr_data),
        .o_nsi_wr_valid   (nsi_wr_valid),
        .o_nsi_wr_last    (nsi_wr_last),

        // The dummy SRAM is modeled as always ready.
        .i_nsi_ready      (1'b1)
    );

    // -------------------------------------------------------------------------
    // DUT 2: NSI Reader to AXI4-Stream
    // -------------------------------------------------------------------------
    vrm_nsi_read2axis #(
        .DATA_W     (DATA_W),
        .ADDR_W     (ADDR_W),
        .FIFO_DEPTH (FIFO_DEPTH)
    ) dut_reader (
        .aclk             (aclk),
        .aresetn          (aresetn),

        .ctrl_start_read  (ctrl_start_read),
        .ctrl_max_addr    (ctrl_max_addr),
        .status_busy      (status_busy),

        .o_nsi_rd_en      (nsi_rd_en),
        .o_nsi_rd_addr    (nsi_rd_addr),
        .i_nsi_rd_data    (nsi_rd_data),

        .m_axis_tdata     (m_axis_tdata),
        .m_axis_tlast     (m_axis_tlast),
        .m_axis_tvalid    (m_axis_tvalid),
        .m_axis_tready    (m_axis_tready)
    );

    // =========================================================================
    // 7. CLOCK GENERATION AND TEST TASKS
    // =========================================================================

    // 100 MHz clock: 10 ns period.
    initial begin
        aclk = 0;
        forever #5 aclk = ~aclk;
    end

    // -------------------------------------------------------------------------
    // AXI4-Stream Data Injection Task
    // -------------------------------------------------------------------------
    // Presents one data item to the AXI4-Stream slave and waits until the
    // receiver asserts TREADY.
    task push_data(
        input [DATA_W-1:0] data,
        input               is_last
    );
    begin
        @(posedge aclk);

        s_axis_tvalid <= 1'b1;
        s_axis_tdata  <= data;
        s_axis_tlast  <= is_last;

        while (!s_axis_tready)
            @(posedge aclk);
    end
    endtask

    // =========================================================================
    // 8. SIMULATION STIMULUS
    // =========================================================================

    integer i = 0;

    initial begin

        // ---------------------------------------------------------------------
        // Waveform Dump
        // ---------------------------------------------------------------------
        $dumpfile("dump_axis_nsi_loopback.vcd");
        $dumpvars(0, tb_vrm_axis_nsi_loopback);

        // ---------------------------------------------------------------------
        // Initial Signal State
        // ---------------------------------------------------------------------
        aresetn          = 1'b0;

        s_axis_tdata     = 0;
        s_axis_tlast     = 0;
        s_axis_tvalid    = 0;

        ctrl_start_read  = 0;
        ctrl_max_addr    = 0;

        // AXI4-Stream master is ready to consume data by default.
        m_axis_tready    = 1;

        // ---------------------------------------------------------------------
        // Reset Sequence
        // ---------------------------------------------------------------------
        #50;
        aresetn = 1'b1;
        #50;

        $display("");
        $display("============================================================");
        $display("VRM AXI4-STREAM <-> NSI LOOPBACK INTEGRATION TEST");
        $display("============================================================");

        // =====================================================================
        // 8.1 AXI4-STREAM TO NSI WRITE TEST
        // =====================================================================

        $display("");
        $display("[TEST] Writing 10 data words through AXI4-Stream to NSI...");

        for (i = 0; i < 10; i = i + 1) begin

            // The final word is marked with TLAST.
            push_data(
                32'hA000_0000 + i,
                (i == 9)
            );

        end

        @(posedge aclk);

        s_axis_tvalid <= 0;
        s_axis_tlast  <= 0;

        // Allow the writer FIFO to drain and all NSI writes to complete.
        repeat(20) @(posedge aclk);

        // =====================================================================
        // 8.2 NSI TO AXI4-STREAM READ TEST
        // =====================================================================

        $display("");
        $display("[TEST] Starting NSI read operation (maximum address = 9)...");

        @(posedge aclk);

        ctrl_max_addr   <= 12'd9;
        ctrl_start_read <= 1'b1;

        @(posedge aclk);

        ctrl_start_read <= 1'b0;

        // =====================================================================
        // 8.3 AXI4-STREAM OUTPUT DATA VERIFICATION
        // =====================================================================

        $display("");
        $display("[TEST] Verifying AXI4-Stream output data...");

        for (i = 0; i < 10; i = i + 1) begin

            while (!m_axis_tvalid)
                @(posedge aclk);

            if (m_axis_tdata !== (32'hA000_0000 + i)) begin

                $display(
                    "[FAIL] Data mismatch: received %h, expected %h",
                    m_axis_tdata,
                    (32'hA000_0000 + i)
                );

            end else begin

                $display(
                    "[PASS] Data[%0d] = %h | TLAST = %b",
                    i,
                    m_axis_tdata,
                    m_axis_tlast
                );

            end

            @(posedge aclk);
        end

        // =====================================================================
        // 8.4 AXI4-STREAM BACKPRESSURE TEST
        // =====================================================================

        $display("");
        $display("[TEST] Testing AXI4-Stream backpressure handling...");

        // Prevent the downstream AXI4-Stream consumer from accepting data.
        m_axis_tready <= 0;

        @(posedge aclk);

        // Read six data words while the output interface is stalled.
        ctrl_max_addr   <= 12'd5;
        ctrl_start_read <= 1'b1;

        @(posedge aclk);

        ctrl_start_read <= 1'b0;

        $display(
            "[INFO] Waiting for the NSI reader to buffer data in the egress FIFO..."
        );

        repeat(50) @(posedge aclk);

        // Re-enable the AXI4-Stream consumer.
        $display(
            "[INFO] Releasing AXI4-Stream backpressure..."
        );

        m_axis_tready <= 1;

        // Verify that buffered data is successfully released after the
        // downstream interface becomes ready.
        for (i = 0; i < 6; i = i + 1) begin

            while (1) begin

                @(posedge aclk);

                if (m_axis_tvalid && m_axis_tready) begin

                    $display(
                        "[PASS] Backpressure recovery: data = %h | TLAST = %b",
                        m_axis_tdata,
                        m_axis_tlast
                    );

                    break;

                end

            end

        end

        // =====================================================================
        // 8.5 END OF TEST
        // =====================================================================

        #100;

        $display("");
        $display("============================================================");
        $display("AXI4-STREAM <-> NSI LOOPBACK VERIFICATION COMPLETED");
        $display("============================================================");
        $display("");

        $finish;

    end

endmodule
